# Generated by Django 5.2.5 on 2025-08-25 12:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('cargo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('diagnostico', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnósticos',
            },
        ),
        migrations.CreateModel(
            name='Duenio',
            fields=[
                ('telefono', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Dueño',
                'verbose_name_plural': 'Dueños',
            },
        ),
        migrations.CreateModel(
            name='Estado_Consulta',
            fields=[
                ('cod_estado', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Estado de Consulta',
                'verbose_name_plural': 'Estados de Consulta',
            },
        ),
        migrations.CreateModel(
            name='Estado_Duenio',
            fields=[
                ('cod_estado', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Estado de Dueño',
                'verbose_name_plural': 'Estados de Dueño',
            },
        ),
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id_med', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('laboratorio', models.CharField(max_length=100)),
                ('fecha_ultima_compra', models.DateField()),
                ('cant_minima', models.IntegerField()),
                ('dosis', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
            },
        ),
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_hist_clinica', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
            ],
            options={
                'verbose_name': 'Perro',
                'verbose_name_plural': 'Perros',
            },
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('raza', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('denominacion', models.CharField(max_length=100)),
                ('cuidados_especiales', models.TextField(blank=True)),
                ('altura_max_hembra', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('altura_min_hembra', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('peso_max_hembra', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('peso_min_hembra', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('altura_max_macho', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('altura_min_macho', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('peso_max_macho', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('peso_min_macho', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Raza',
                'verbose_name_plural': 'Razas',
            },
        ),
        migrations.CreateModel(
            name='Sintomas',
            fields=[
                ('sintoma', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Síntoma',
                'verbose_name_plural': 'Síntomas',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Documento',
            fields=[
                ('tipo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
            },
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('vacuna', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('laboratorio', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('dosisxgramo', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Vacuna',
                'verbose_name_plural': 'Vacunas',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=100)),
                ('barrio', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
                'constraints': [models.UniqueConstraint(fields=('calle', 'barrio', 'numero', 'ciudad', 'pais'), name='unique_direccion')],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('matricula_habilitante', models.CharField(blank=True, max_length=50, null=True)),
                ('numDoc', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_ingreso', models.DateField()),
                ('es_supervisor', models.BooleanField(default=False)),
                ('es_supervisor_suplente', models.BooleanField(default=False)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sabueso_feliz.cargo')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_consulta', models.IntegerField()),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('peso_actual', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('altura_actual', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('sintomas_detectados', models.TextField(blank=True)),
                ('descripcion_sintoma', models.TextField(blank=True)),
                ('diagnostico', models.CharField(max_length=100)),
                ('descripcion_diagnostico', models.TextField(blank=True)),
                ('estado', models.CharField(max_length=100)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sabueso_feliz.empleado')),
                ('perro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sabueso_feliz.perro')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
            },
        ),
        migrations.CreateModel(
            name='Historial_Consulta',
            fields=[
                ('cod_hist_estado', models.AutoField(primary_key=True, serialize=False)),
                ('historial', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('cod_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sabueso_feliz.estado_consulta')),
            ],
            options={
                'verbose_name': 'Historial de Consulta',
                'verbose_name_plural': 'Historiales de Consulta',
            },
        ),
        migrations.CreateModel(
            name='PerroxDuenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sabueso_feliz.duenio')),
                ('perro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sabueso_feliz.perro')),
            ],
            options={
                'verbose_name': 'Perro por Dueño',
                'verbose_name_plural': 'Perros por Dueño',
            },
        ),
        migrations.CreateModel(
            name='Historial_Duenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('duenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sabueso_feliz.duenio')),
                ('perro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sabueso_feliz.perro')),
                ('perroxduenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sabueso_feliz.perroxduenio')),
            ],
            options={
                'verbose_name': 'Historial de Dueño',
                'verbose_name_plural': 'Historiales de Dueño',
            },
        ),
        migrations.AddField(
            model_name='perro',
            name='raza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sabueso_feliz.raza'),
        ),
        migrations.CreateModel(
            name='SintomasxConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sabueso_feliz.consultas')),
                ('sintoma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sabueso_feliz.sintomas')),
            ],
            options={
                'verbose_name': 'Síntoma por Consulta',
                'verbose_name_plural': 'Síntomas por Consulta',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sabueso_feliz.direccion')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('cod_stock', models.AutoField(primary_key=True, serialize=False)),
                ('cant_stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cant_min_sucursal', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sabueso_feliz.medicamentos')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sabueso_feliz.sucursal')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
        migrations.AddField(
            model_name='perro',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sabueso_feliz.sucursal'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sabueso_feliz.sucursal'),
        ),
        migrations.AddField(
            model_name='consultas',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sabueso_feliz.sucursal'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipoDoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sabueso_feliz.tipo_documento'),
        ),
        migrations.CreateModel(
            name='Calendario_Vacunas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada_vacuna', models.DateField()),
                ('fecha_real_vacuna', models.DateField(blank=True, null=True)),
                ('dosis', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sabueso_feliz.empleado')),
                ('perro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sabueso_feliz.perro')),
                ('vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sabueso_feliz.vacuna')),
            ],
            options={
                'verbose_name': 'Calendario de Vacunas',
                'verbose_name_plural': 'Calendarios de Vacunas',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticoxConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sabueso_feliz.consultas')),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sabueso_feliz.diagnostico')),
            ],
            options={
                'verbose_name': 'Diagnóstico por Consulta',
                'verbose_name_plural': 'Diagnósticos por Consulta',
                'constraints': [models.UniqueConstraint(fields=('diagnostico', 'consulta'), name='unique_diagnosticoxconsulta')],
            },
        ),
        migrations.CreateModel(
            name='Medicamentos_Recetados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodicidad', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sabueso_feliz.consultas')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sabueso_feliz.medicamentos')),
            ],
            options={
                'verbose_name': 'Medicamento Recetado',
                'verbose_name_plural': 'Medicamentos Recetados',
                'constraints': [models.UniqueConstraint(fields=('medicamento', 'consulta'), name='unique_medicamentos_recetados')],
            },
        ),
        migrations.AddConstraint(
            model_name='perroxduenio',
            constraint=models.UniqueConstraint(fields=('perro', 'duenio'), name='unique_perroxduenio'),
        ),
        migrations.AddConstraint(
            model_name='historial_duenio',
            constraint=models.UniqueConstraint(fields=('perroxduenio', 'perro', 'duenio'), name='unique_historial_duenio'),
        ),
        migrations.AddConstraint(
            model_name='sintomasxconsulta',
            constraint=models.UniqueConstraint(fields=('consulta', 'sintoma'), name='unique_sintomasxconsulta'),
        ),
        migrations.AddConstraint(
            model_name='sucursal',
            constraint=models.UniqueConstraint(fields=('direccion',), name='unique_sucursal'),
        ),
        migrations.AddIndex(
            model_name='perro',
            index=models.Index(fields=['num_hist_clinica', 'sucursal'], name='sabueso_fel_num_his_054861_idx'),
        ),
        migrations.AddConstraint(
            model_name='perro',
            constraint=models.UniqueConstraint(fields=('num_hist_clinica', 'sucursal'), include=('num_hist_clinica', 'sucursal'), name='unique_perro'),
        ),
        migrations.AddConstraint(
            model_name='consultas',
            constraint=models.UniqueConstraint(fields=('perro', 'num_consulta', 'sucursal'), name='unique_consulta'),
        ),
        migrations.AddConstraint(
            model_name='calendario_vacunas',
            constraint=models.UniqueConstraint(fields=('perro', 'vacuna'), name='unique_calendario_vacunas'),
        ),
    ]
