# Generated by Django 5.2.5 on 2025-08-25 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabueso_feliz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultas',
            name='descripcion_diagnostico',
        ),
        migrations.RemoveField(
            model_name='consultas',
            name='descripcion_sintoma',
        ),
        migrations.AddField(
            model_name='consultas',
            name='med_recetados',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sabueso_feliz.medicamentos_recetados'),
        ),
        migrations.AddField(
            model_name='diagnosticoxconsulta',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='perroxduenio',
            name='estado',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sabueso_feliz.estado_duenio'),
        ),
        migrations.AddField(
            model_name='perroxduenio',
            name='fecha_fin',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='perroxduenio',
            name='fecha_inicio',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='sintomasxconsulta',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Historial_Duenio',
        ),
    ]
